// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AnalysisProgress: typeof import('./src/components/analysis/AnalysisProgress.vue')['default']
    AnalysisResults: typeof import('./src/components/analysis/AnalysisResults.vue')['default']
    CodestyleSubview: typeof import('./src/components/analysis/subviews/CodestyleSubview.vue')['default']
    FilesSubview: typeof import('./src/components/analysis/subviews/FilesSubview.vue')['default']
    FormatingSubview: typeof import('./src/components/analysis/subviews/FormatingSubview.vue')['default']
    'ICib:pypi': typeof import('~icons/cib/pypi')['default']
    'IClarity:dashboardOutlineBadged': typeof import('~icons/clarity/dashboard-outline-badged')['default']
    'IEosIcons:bubbleLoading': typeof import('~icons/eos-icons/bubble-loading')['default']
    'IEosIcons:loading': typeof import('~icons/eos-icons/loading')['default']
    'IFaSolid:moon': typeof import('~icons/fa-solid/moon')['default']
    'IFaSolid:sun': typeof import('~icons/fa-solid/sun')['default']
    'IFluent:clipboardCode24Regular': typeof import('~icons/fluent/clipboard-code24-regular')['default']
    'IIc:sharpFormatIndentDecrease': typeof import('~icons/ic/sharp-format-indent-decrease')['default']
    'IIcomoonFree:info': typeof import('~icons/icomoon-free/info')['default']
    'IIconParkOutline:analysis': typeof import('~icons/icon-park-outline/analysis')['default']
    'IIconParkOutline:folderSuccess': typeof import('~icons/icon-park-outline/folder-success')['default']
    'ILogos:python': typeof import('~icons/logos/python')['default']
    'IMaterialSymbols:check': typeof import('~icons/material-symbols/check')['default']
    'IMaterialSymbols:circle': typeof import('~icons/material-symbols/circle')['default']
    'IMaterialSymbols:playArrowOutline': typeof import('~icons/material-symbols/play-arrow-outline')['default']
    'IMaterialSymbols:settingsOutlineRounded': typeof import('~icons/material-symbols/settings-outline-rounded')['default']
    'IPh:files': typeof import('~icons/ph/files')['default']
    'ISimpleIcons:adguard': typeof import('~icons/simple-icons/adguard')['default']
    'ITeenyicons:folderOutline': typeof import('~icons/teenyicons/folder-outline')['default']
    'ITeenyicons:folderTickOutline': typeof import('~icons/teenyicons/folder-tick-outline')['default']
    'ITeenyicons:pythonOutline': typeof import('~icons/teenyicons/python-outline')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheSidebar: typeof import('./src/components/TheSidebar.vue')['default']
    TheTabsbar: typeof import('./src/components/TheTabsbar.vue')['default']
    TypingSubview: typeof import('./src/components/analysis/subviews/TypingSubview.vue')['default']
  }
}
